server:
  error:
    include-message: always

chatgpt:
  base-url: https://api.openai.com/v1
  model: gpt-4o-mini
  api-key: ${OPENAI_API_KEY:}

logging:
  level:
    root: INFO
    com.leetmate: INFO
